# Generated by Django 5.1.1 on 2024-09-20 16:28

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Id Cuenta')),
                ('account_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Numero Cuenta')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TypeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('account_type', models.CharField(choices=[('1', 'Ahorros'), ('2', 'Corriente'), ('3', 'Nomina'), ('4', 'Pension'), ('5', 'Infantil'), ('6', 'Joven')], default='1', max_length=1, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Tipo Cuenta',
                'verbose_name_plural': 'Tipos Cuenta',
                'ordering': ['-created'],
            },
        ),
    ]
