# Generated by Django 5.1.1 on 2024-09-20 16:28

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('card', '0001_initial'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(verbose_name='Fecha Transacion')),
                ('destination_account', models.CharField(max_length=100, verbose_name='Cuenta Destino')),
                ('transaction_amount', models.IntegerField(verbose_name='Monto de Transaccion')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_account', to='account.account')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_card', to='card.card')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_operation', to='operation.operation')),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transacciones',
            },
        ),
    ]
