# Generated by Django 5.1.1 on 2024-09-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Codigo de activacion'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='OTP Creado'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_otp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OTP Login'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OTP 32'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_login_otp',
            field=models.BooleanField(default=False, verbose_name='Login Usado'),
        ),
    ]
